export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_CHANGE_ADDRESS = 'USER_CHANGE_ADDRESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGIN_LOADING = 'AUTH_LOGIN_LOADING';
export const AUTH_LOADING_FINISHED = 'AUTH_LOADING_FINISHED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAILED = 'VERIFICATION_FAILED';

export const CLEAN_ERROR = 'CLEAN_ERROR';

// ADMIN 

export const ALL_CATEGORY = 'ALL_CATEGORY';
export const ALL_PRODUCT = 'ALL_PRODUCT';
export const ADMIN_LOADING = 'ADMIN_LOADING';
export const ADMIN_LOADING_FINISHED = 'ADMIN_LOADING_FINISHED';
export const ADMIN_LOADING_ERROR = 'ADMIN_LOADING_ERROR';

export const ADMIN_CLEAN = 'ADMIN_CLEAN'

// CART 
export const SHOW_CART = 'SHOW_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_CART = 'DELETE_CART';
export const CLEAR_CART = 'CLEAR_CART';

//TRANSACTION
export const GET_ALL_TRANSACTION = 'GET_ALL_TRANSACTION'
export const SEND_TO_TRANSACTION = 'SEND_TO_TRANSACTION';
export const CLEAR_TRANSACTION = 'CLEAR_TRANSACTION';
export const CLEAR_DETAIL_AND_SELECTED = 'CLEAR_DETAIL_AND_SELECTED'